# Chapter 9 Exercises
## Quantum Algorithms

In [1]:
import numpy as np

### <font color='blue'>9.1</font> *Using the matrix representation of the Hadamard gate*
### $ H = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 & 1 \\ 1 & -1 \\ \end{pmatrix} $
### *Write down the matrix for* $H \otimes H$ *and find* $(H \otimes H)(|0⟩ \otimes|1⟩)$*. Show that this is equivalent to*
###  $ |\phi⟩ =  \left( \frac{|0⟩ + |1⟩}{\sqrt{2}} \right) \left( \frac{|0⟩ - |1⟩}{\sqrt{2}} \right) $

In [2]:
H = 1/np.sqrt(2) * np.array([[1, 1],[1, -1]])
kronHH = np.kron(H,H)
print(kronHH)

[[ 0.5  0.5  0.5  0.5]
 [ 0.5 -0.5  0.5 -0.5]
 [ 0.5  0.5 -0.5 -0.5]
 [ 0.5 -0.5 -0.5  0.5]]


In [3]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
kron01 = np.kron(zero, one)
phi1, phi2 = 1/np.sqrt(2)*(zero+one), 1/np.sqrt(2)*(zero-one)
phi = np.kron(phi1,phi2)
phi == np.matmul(kronHH, kron01)

array([[ True],
       [ True],
       [ True],
       [ True]])

### <font color='green'>Answer: $H \otimes H = \begin{pmatrix} \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} \end{pmatrix} \ , \ |\phi⟩ = (H \otimes H)(|0⟩ \otimes|1⟩) = \begin{pmatrix} \frac{1}{2} \\ -\frac{1}{2} \\ \frac{1}{2} \\ -\frac{1}{2} \end{pmatrix} $

### <font color='blue'>9.2</font> *The Beam splitter gate has a matrix representation given by*
### $ B = \frac{1}{\sqrt{2}} \begin{pmatrix} i & 1 \\ 1 & i \\ \end{pmatrix} $
### *Show that B generates superposition states out of the computational basis states $|0⟩$	and $|1⟩$. In particular, show that*
### $ B \otimes B |0⟩ |0⟩ = \left( \frac{i|0⟩ + |1⟩}{\sqrt{2}} \right) \left( \frac{i|0⟩ + |1⟩}{\sqrt{2}} \right) $

In [4]:
phi1 = phi2 = 1/np.sqrt(2) * ((1j*zero)+one)
phi = np.kron(phi1,phi2)
B = 1/np.sqrt(2) * np.array([[1j, 1],[1, 1j]])
kronBB = np.kron(B,B)
prod00 = np.kron(zero,zero)
np.matmul(kronBB, prod00) == phi

array([[ True],
       [ True],
       [ True],
       [ True]])

### <font color='green'>Answer: $ B \otimes B |0⟩ |0⟩ = \left( \frac{i|0⟩ + |1⟩}{\sqrt{2}} \right) \left( \frac{i|0⟩ + |1⟩}{\sqrt{2}} \right) = \begin{pmatrix} -\frac{1}{2} \\ \frac{i}{2} \\ \frac{i}{2} \\ \frac{1}{2} \end{pmatrix} $

### <font color='blue'>9.3</font> *Show that the matrix representation of HP($\theta$)HP($\phi$) is given by*
### $ e^{i\theta/2} \begin{pmatrix} \cos{\theta/2} & -ie^{i\theta}\sin{\theta/2} \\ -i\sin{\theta/2} & e^{i\theta}\cos{\theta/2} \\ \end{pmatrix} $

In [5]:
theta = np.pi
H, P = 1/np.sqrt(2) * np.array([[1, 1],[1, -1]]), np.array([[1, 0],[0, np.exp(1j*theta)]])  
given_by = np.exp(1j*theta/2) * np.array([[np.cos(theta/2), -1j*np.exp(1j*theta)*np.sin(theta/2)],[-1j*np.sin(theta/2), np.exp(theta/2)*np.cos(theta/2)]])
HP_HP = np.matmul(np.matmul(H,P),np.matmul(H,P))
np.round(HP_HP) == np.round(given_by)

array([[ True,  True],
       [ True,  True]])

### <font color='blue'>9.4</font> *Derive (9.17) through (9.19).*

In [6]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
prod01, prod10, prod11 = np.kron(zero,one), np.kron(one,zero), np.kron(one,one)