# Chapter 4 Exercises
## Tensor Products

In [1]:
import numpy as np

### <font color='blue'>4.1</font> *Consider the basis in Example 4.1 Show that it is orthonormal.*

In [2]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
w1 = np.inner(zero,zero)
w2 = np.inner(zero,one)
w3 = np.inner(one,zero)
w4 = np.inner(one,one)

### <font color='green'>Answer: $⟨w_i|w_i⟩ = 1 , ⟨w_i|w_j⟩ = 0 $

### <font color='blue'>4.1</font> *Returning to Example 4.1, show that* $⟨w_3|w_4⟩ = ⟨w_4|w_4w_3⟩ = 0$

In [3]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
w3, w4 = np.squeeze(np.kron(one, zero)), np.squeeze(np.kron(one, one))
0 == np.dot(w3,w4) == np.dot(w4, w4*w3)

True

### <font color='blue'>4.3</font> *Given that $⟨a|b⟩	 = 1/2$ and $⟨c|d⟩ = 3/4$, calculate $⟨\psi|\phi⟩$, where $|\psi⟩	 = |a⟩\otimes|c⟩$	and $|\phi⟩ = |b⟩\otimes|d⟩$	.*

In [4]:
1/2*1/4 #Equ 4.8

0.125

### <font color='green'>Answer: $⟨\psi|\phi⟩ = \frac{1}{8}$

### <font color='blue'>4.4</font> *Calculate the tensor product of* $ \ |\psi⟩ = \frac{1}{\sqrt{2}} \begin{pmatrix} 1 \\ 1 \end{pmatrix} \ $*and*$ \ |\phi⟩ = \frac{1}{2} \begin{pmatrix} 1 \\ \sqrt{3} \end{pmatrix}$

In [5]:
psi = 1/np.sqrt(2) * np.array([[1],[1]])
phi = 1/2 * np.array([[1],[np.sqrt(3)]])
kron = np.kron(psi, phi)
print(kron.reshape(2,2))

[[0.35355339 0.61237244]
 [0.35355339 0.61237244]]


### <font color='green'>Answer: $|\psi⟩\otimes|\phi⟩ = \begin{pmatrix} \frac{1}{2\sqrt{2}} & \frac{\sqrt{\frac{3}{2}}}{2} \\ \frac{1}{2\sqrt{2}} & \frac{\sqrt{\frac{3}{2}}}{2} \\ \end{pmatrix} $

### <font color='blue'>4.5</font> *Can* $|\psi⟩ = \frac{1}{2} (|0⟩|0⟩ - |0⟩|1⟩ - |1⟩|0⟩ - |1⟩|1⟩)$ *be written as a product state?*

In [6]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
psi = (np.outer(zero,zero)-np.outer(zero,one)-np.outer(one,zero)-np.outer(one,one))/(2)
kron = np.kron(zero-one, zero-one)
kron.reshape(2,2)*0.5 == psi

array([[ True,  True],
       [ True, False]])

### <font color='green'> Answer: No

### <font color='blue'>4.6</font> *Can* $|\psi⟩ = \frac{|0⟩|0⟩ + |1⟩|1⟩}{\sqrt{2}}$ *be written as a product state?*

In [7]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
psi = (np.outer(zero,zero)+np.outer(one,one))/np.sqrt(2)
kron = np.kron(zero, zero) + np.kron(one, one)
kron.reshape(2,2)/np.sqrt(2) == psi

array([[ True,  True],
       [ True,  True]])

### <font color='green'> Answer: No, it can only be written as the sum of two product states.

### <font color='blue'>4.7</font> *Find* $X\otimes Y|\psi⟩$*, where* $|\psi⟩ = \frac{|0⟩|1⟩ - |1⟩|0⟩}{\sqrt{2}}$

In [8]:
X, Y = np.array([[0,1], [1,0]]), np.array([[0,-1j], [1j,0]])
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
psi = (np.outer(zero,one)-np.outer(one,zero))/np.sqrt(2)
Ypsi = np.matmul(Y,psi)
kron = np.kron(X, Ypsi)
print(kron)

[[0.+0.j         0.+0.j         0.+0.70710678j 0.+0.j        ]
 [0.+0.j         0.+0.j         0.+0.j         0.+0.70710678j]
 [0.+0.70710678j 0.+0.j         0.+0.j         0.+0.j        ]
 [0.+0.j         0.+0.70710678j 0.+0.j         0.+0.j        ]]


### <font color='green'>Answer: $X \otimes Y|\psi⟩ = \begin{pmatrix} 0 & 0 & \frac{i}{\sqrt{2}} & 0 \\ 0 & 0 & 0 & \frac{i}{\sqrt{2}} \\ \frac{i}{\sqrt{2}} & 0 & 0 & 0 \\ 0 & \frac{i}{\sqrt{2}} & 0 & 0 \end{pmatrix} $

### <font color='blue'>4.8</font> *Show that $(A\otimes B)^\dagger =A^\dagger \otimes B^\dagger$.*

In [9]:
A = np.array([[27j,36],[42,55j]])
B = np.array([[64,72j],[81j,97]])
np.conj(np.kron(A,B)) == np.kron(np.conj(A), np.conj(B))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### <font color='blue'>4.9</font> *If* $|\psi⟩ = \frac{|00⟩ - |11⟩}{\sqrt{2}}$, *find* $I \otimes Y|\psi⟩$

In [10]:
I, Y = np.array([[1,0], [0,1]]), np.array([[0,-1j], [1j,0]])
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
psi = (np.outer(zero,one)+np.outer(one,zero))/np.sqrt(2)
Ypsi = np.matmul(Y,psi)
kron = np.kron(I, Ypsi)
print(kron)

[[0.-0.70710678j 0.+0.j         0.+0.j         0.+0.j        ]
 [0.+0.j         0.+0.70710678j 0.+0.j         0.+0.j        ]
 [0.+0.j         0.+0.j         0.-0.70710678j 0.+0.j        ]
 [0.+0.j         0.+0.j         0.+0.j         0.+0.70710678j]]


### <font color='green'>Answer: $I \otimes Y|\psi⟩ = \begin{pmatrix} -\frac{i}{\sqrt{2}} & 0 & 0 & 0 \\ 0 & \frac{i}{\sqrt{2}} & 0 & 0 \\ 0 & 0 & -\frac{i}{\sqrt{2}} & 0 \\ 0 & 0 & 0 & \frac{i}{\sqrt{2}} \end{pmatrix} $

### <font color='blue'>4.10</font> *Calculate the matrix representation of $X \otimes Y$.*

In [11]:
X, Y = np.array([[0,1], [1,0]]), np.array([[0,-1j], [1j,0]])
kron = np.kron(X,Y)
print(kron)

[[0.+0.j 0.-0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.-0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]]


### <font color='green'>Answer: $X \otimes Y = \begin{pmatrix} 0 & 0 & 0 & -i \\ 0 & 0 & i & 0 \\ 0 & -i & 0 & 0 \\ i & 0 & 0 & 0 \end{pmatrix} $