# Chapter 8 Exercises
## Quantum Gates and Circuits

In [1]:
import numpy as np

### <font color='blue'>8.1</font>  *Describe the action of the Y gate in terms of the Bloch sphere picture.*

### <font color='green'> (B) Answer: The Y gate shifts angles by one radian.

### <font color='blue'>8.2</font>  *The Hubbard operators are given by*
### $X^{11} = |0⟩⟨0| \ , \ X^{12} = |0⟩⟨1| \ , \ X^{21} = |1⟩⟨0| \ , \ X^{22} = |1⟩⟨1| $
### *(A) Write down the matrix representations of the Hubbard operators in the computational basis.*
### *(B) Describe the action of the Hubbard operators on the Hadamard basis states.*

In [2]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
x11, x12 = np.outer(zero,zero), np.outer(zero,one)
x21, x22 = np.outer(one,zero),np.outer(one,one)
print(x11)

[[1 0]
 [0 0]]


### <font color='green'> (A) Answer: $ X^{11} = \begin{pmatrix} 1 & 0 \\ 0 & 0 \end{pmatrix} \ , \ X^{12} = \begin{pmatrix} 0 & 1 \\ 0 & 0 \\ \end{pmatrix} \ , \ X^{21} = \begin{pmatrix} 0 & 0 \\ 1 & 0 \\ \end{pmatrix} \ , \ X^{22} = \begin{pmatrix} 0 & 0 \\ 0 & 1 \\ \end{pmatrix} $

In [3]:
plus, minus = (zero+one)/np.sqrt(2), (zero-one)/np.sqrt(2)
print(np.matmul(x11,plus))

[[0.70710678]
 [0.        ]]


### <font color='green'> (B) Answer: $X^{11}$ and $X^{12}$ remove the second element. $X^{21}$ and $X^{22}$ remove the first element. 

### <font color='blue'>8.3</font>  *Find a way to write the Pauli operators X, Y, and Z in terms of the Hubbard operators.*

In [4]:
X, Y, Z = np.array([[0,1], [1,0]]), np.array([[0,-1j], [1j,0]]), np.array([[1,0], [0,-1]])
X == x21 + x12
Y == 1j*x21 -1j*x12
Z == x11 - x22

array([[ True,  True],
       [ True,  True]])

### <font color='green'>Answer: $ X = X^{21}+X^{12} \ , \ Y = iX^{21}-iX^{12} \ , \ Z = X^{11}-X^{22} $

### <font color='blue'>8.4</font>  *Show that the controlled NOT gate is Hermitian and unitary.*

In [5]:
cnot = np.array([[1,0,0,0], [0,1,0,0],[0,0,0,1],[0,0,1,0]]) #Equ 8.28
cnot_adj = np.conj(np.transpose(cnot))
cnot == cnot_adj #Hermitian check, Equ 3.32
np.matmul(cnot, cnot_adj) == np.matmul(cnot_adj, cnot) #Unitary check, Equ 3.34

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### <font color='green'>Answer: $CN = CN^\dagger  \ , \  CN \ CN^\dagger = CN^\dagger CN = I $

### <font color='blue'>8.5</font>  *Let $|a⟩=|1⟩$	, and consider the circuit shown in Figure 8.5. Determine which Bell states are generated as output when $|b⟩=|0⟩,|b⟩=|1⟩$	.*

In [6]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
a, b0, b1 = one, zero, one
Bab_0 = 1/np.sqrt(2) * np.kron(zero,b0) + (-1)*(np.kron(one,zero)) #Same as Equ 8.33
Bab_1 = 1/np.sqrt(2) * np.kron(zero,b1) + (-1)*(np.kron(one,zero)) #Does not match Equ.
Bab_0

array([[ 0.70710678],
       [ 0.        ],
       [-1.        ],
       [ 0.        ]])

### <font color='green'>Answer: When $|b⟩ = 1 \ , \ |\beta_{11}⟩$ is generated

### <font color='blue'>8.6</font> *Write down the matrix representation for the controlled Z gate. Then write down its representation using Dirac notation.*


In [7]:
Z = np.array([[1,0], [0,-1]])
H = 1/np.sqrt(2) * np.array([[1, 1],[1, -1]])
np.kron(Z,Z)

array([[ 1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0,  1]])

### <font color='green'>Answer: $CZ = \begin{pmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & -1 \end{pmatrix} $

### <font color='blue'>8.7</font> *Consider the single qubit operators X, Y, Z, S, and T. Find the square of each operator.*


In [8]:
X, Y, Z = np.array([[0,1], [1,0]]), np.array([[0,-1j], [1j,0]]), np.array([[1,0], [0,-1]])
S, T = np.array([[1,0], [0,1j]]), np.array([[1,0], [0,np.exp(1j*np.pi/4)]]) 
np.round(T**2) 

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 0.+1.j]])

### <font color='green'>Answer: $ X^2 = X \ , \ Y^2 = -X \ , \ Z^2 = |Z| \ , \ S^2 = Z \ , \ T^2 = \begin{pmatrix} 1 &  0 \\ 0 & 0 \\ \end{pmatrix} ,$