# Chapter 5 Exercises
## The Density Operator

In [26]:
import numpy as np

### <font color='blue'>5.1</font> *Consider the following state vector:*
### $|\psi⟩ = \sqrt{\frac{5}{6}}|0⟩ + \frac{1}{\sqrt{6}}|1⟩ $
### *(A) Is the state normalized?* 
### *(B) What is the probability that the system is found to be in state $|0⟩$ if Z is measured?*
### *(C) Write down the density operator.* 
### *(D) Find the density matrix in the {$|0⟩,|1⟩$} basis, and show that $Tr(\rho)=1$.*

In [27]:
5/6+1/6 == 1

True

### <font color='green'> (A) Answer: Yes, the state is normalized.

In [28]:
np.sqrt(5/6)**2

0.8333333333333334

### <font color='green'> (B) Answer: Pr(0) = $\frac{5}{6}$

In [29]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
psi = np.sqrt(5/6)*zero + np.sqrt(1/6)*one
p = np.outer(psi,psi)
print(p)

[[0.83333333 0.372678  ]
 [0.372678   0.16666667]]


### <font color='green'> (C) Answer: $\rho = |\psi⟩⟨\psi| = \begin{pmatrix} \frac{5}{6} & \frac{\sqrt{5}}{6} \\ \frac{\sqrt{5}}{6} & \frac{1}{6} \\ \end{pmatrix} $

In [30]:
np.trace(p) == 1

True

### <font color='blue'>5.2</font> *Consider the state*
### $|\psi⟩ = \begin{pmatrix} \cos\theta \\ i\sin\theta \end{pmatrix}$
### *Is this state normalized? Is* $\rho = |\psi⟩⟨\psi|$ *a density operator?*

In [31]:
np.cos(55)**2 + np.sin(55)**2 == 1
np.cos(55)**2 + 1j*np.sin(55)**2 == 1

False

### <font color='green'> Answer: No, the state is not normalized, because $\cos^2\theta + i\sin^2\theta \neq 1.$

In [32]:
cos, isin = np.cos(55), 1j*np.sin(55)
psi = np.array([[cos],[isin]]) 
psi

array([[ 0.02212676+0.j        ],
       [-0.        -0.99975517j]])

In [33]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
cos, isin = np.cos(55), 1j*np.sin(55)
psi = cos*zero + isin*one
p = np.outer(psi, psi)
np.trace(p) == 1 #True
np.transpose(np.conj(p)) == p #False

array([[ True, False],
       [False,  True]])

### <font color='green'> Answer: No, $\rho$ is not a density operator. $|\psi⟩$ is complex, so $\rho$ cannot be Hermitian.

### <font color='blue'>5.3</font> *Let*
### $|\psi⟩ = \sqrt{\frac{3}{7}}|0⟩ + \frac{2}{\sqrt{7}}|1⟩ $
### *(A) Write down the density matrix in the* {$|0⟩,|1⟩$} *basis.*
### *(B) Determine whether or not this is a pure state.*
### *(C) Write down the density matrix in the {$|+⟩, |−⟩$} basis, show that Tr(ρ) =1 still holds, and determine if you still obtain the same result as in part (b).*

In [34]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
psi = np.sqrt(3/7)*zero + np.sqrt(4/7)*one
p = np.outer(psi,psi)
print(p)

[[0.42857143 0.49487166]
 [0.49487166 0.57142857]]


### <font color='green'> (A) Answer: $\rho = |\psi⟩⟨\psi| = \begin{pmatrix} \frac{3}{7} & \frac{2\sqrt{3}}{7} \\ \frac{2\sqrt{3}}{7} & \frac{4}{7} \\ \end{pmatrix} $

In [35]:
np.trace(p**2) == 1

False

### <font color='green'> (B) Answer: No, this is not a pure state, because $Tr(\rho^2) \neq 1.$

### <font color='green'> (C) Answer: 

### <font color='blue'>5.4</font> *Suppose that a system is in the state*
### $|\psi⟩ = \sqrt{\frac{2}{3}}|0⟩ + \frac{1}{\sqrt{3}}|1⟩ $
### *(A) Compute* $Tr(\rho)$ *and* $Tr(\rho^2)$*. Is this a mixed state?*
### *(B) Find $⟨X⟩$	for this state.*

In [36]:
zero, one = np.array([[1],[0]]), np.array([[0],[1]])
psi = np.sqrt(2/3)*zero + np.sqrt(1/3)*one
p = np.outer(psi,psi)
print(np.trace(p), np.trace(p**2))

1.0 0.5555555555555556


### <font color='green'> (A) Answer: Yes, this is a mixed state, because $Tr(\rho^2) < 1.$

In [40]:
X = np.array([[0,1], [1,0]])
Xp = np.matmul(X,p)
np.trace(Xp)

0.9428090415820634

### <font color='green'> (B) Answer: $⟨X⟩ = Tr(X\rho) = \frac{2\sqrt{2}}{3}$	

### <font color='blue'>5.5</font> *Suppose that*